version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_crm
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm_perfumeria
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_crm
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: crm_perfumeria

  frontend:
    image: nginx:latest
    container_name: frontend_crm
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
